# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6fa1d074b17bf6eb827763f589136941888bbd1916269b9a8927d50a090c8eb595160d34fa81a1026139a4bcf225aacc40777a78c82e304a7a3c93193751e7

test:
  secret_key_base: 71b0aef5b693af54318ecae75dffe74107a9b1c7ac659466588f83faf77a758c6289f9083442bb90b61d243c61554e41fce96656608d7cedf5d76825ea2f25f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
